/// Flutter icons AppIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';
  static const String? _kFontPkg = null;

  static const IconData search = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_circled = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_open = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData login = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_off = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData picture = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_alt = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tags = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData retweet = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrows_cw = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData floppy = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_circled = IconData(0xf0a8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_circled = IconData(0xf0a9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_circled = IconData(0xf0aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_circled = IconData(0xf0ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_alt = IconData(0xf0f3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_up_alt = IconData(0xf164, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_down_alt = IconData(0xf165, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_pdf = IconData(0xf1c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_image = IconData(0xf1c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData history = IconData(0xf1da, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photo = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vcard = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attention = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData users_outline = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog_outline = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu_outline = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_bar = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData picture_1 = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData users_1 = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_bars = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sad = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData users = IconData(0xf0c0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_empty = IconData(0xf0e6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_line = IconData(0xf201, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData expeditedssl = IconData(0xf23e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData telegram = IconData(0xf2c6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tasklist = IconData(0xf31c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_discussion = IconData(0xf3c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData telegram_plane = IconData(0xf3fe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_dots = IconData(0xf4ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_slash = IconData(0xf4b3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_cog = IconData(0xf4fe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_edit = IconData(0xf4ff, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_lock = IconData(0xf502, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tired = IconData(0xf5c8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData envelope_open_text = IconData(0xf658, fontFamily: _kFontFam, fontPackage: _kFontPkg);

}
